dist: focal
language: python
python:
    - 3.9
    - 3.10-dev
git:
    # Commit history is required for update tests
    depth: false
services:
    - redis
before_install:
    - nvm use v12.7.0
install:
    - make deps
    - make deps-dev
script:
    - make test
    - make test-ext
    # Skip code style checks if WIP is indicated
    - test -z "${TRAVIS_COMMIT_MESSAGE##*WIP*}" || make lint
jobs:
    include:
        - &test-ui
          stage: test-ui
          addons:
              sauce_connect:
                  username: {sauce-user}
              jwt:
                  secure: {sauce-access-key-encrypted}
          script: make test-ui WEBDRIVER_URL="https://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com/wd/hub" TUNNEL_ID="$TRAVIS_JOB_NUMBER" SUBJECT="#$TRAVIS_JOB_NUMBER"
          env: BROWSER=chrome PLATFORM="Windows 10"
        - <<: *test-ui
          env: BROWSER=MicrosoftEdge PLATFORM="Windows 10"
        - <<: *test-ui
          env: BROWSER=firefox PLATFORM="Windows 10"
        - <<: *test-ui
          env: BROWSER=safari PLATFORM="macOS 11"
